version: 2.1

jobs:
  execute:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - restore_cache:
          name: Restore npm dependencies
          keys:
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            - v1-npm-deps-
      - run:
          name: Install npm dependencies
          command: npm install
      - save_cache:
          name: Cache npm dependencies
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - ~/workspace/node_modules
      - run:
          name: Run main
          command: npm run start

workflows:
  version: 2
  execute-workflow:
    triggers:
      - schedule:
          cron: "* * * *" # UTC
          filters:
            branches:
              only:
                - master
    jobs:
      - execute
